# Generated by Django 3.1.6 on 2021-03-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210217_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='bio',
            field=models.TextField(blank=True, help_text='Enter your bio details here.', max_length=400),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='prof_picture',
            field=models.ImageField(default='default.jpg', upload_to='pp_pics/'),
        ),
    ]
